{
    "name": "Throw Exception",
    "definition": "Function _print_ call _inverse_ which throw exception as parameter passed by HTML form.",
    "family": "code_pattern_js",
    "tags": [],
    "instances": [
        "./1_instance_98_throw_exception/1_instance_98_throw_exception.json",
        "./2_instance_98_throw_exception/2_instance_98_throw_exception.json"
    ]
}